### ISSUE TITLE
Develop Korok Seed Location Database 1.2

### ISSUE THREAD

**Issue by jayakumar0812** [jayakumar0812/Zelda#3]
## Sub-Issue: Develop Korok Seed Location Database
**Description:** Create a database to store and retrieve Korok seed locations.

**Tasks:**
- [x] Structure the database schema.
- [x] Populate the database with all 900 Korok seed locations.
- [x] Ensure data can be queried efficiently.
